---
title: "sitio_01"
---


# Cadenas de Markov y movilidad social

## Motivaciones

Este sitio surge de querer entender las relaciones entre las cadenas de Markov, los valores y vectores propios y el modelado de procesos sociales.

## Cadenas de Markov

Una de sus propiedades es que son *memoryless*, es decir, el pasado no influye en el resultado futuro, sino que únicamente intervine el presente.

En los modelos en cuestión el futuro se resume en el presente como un *estado*, el cual emerge con el paso del tiempo con cierta probabilidad


------------------------------------------------------------------------

## Especificación de modelos de Markov

Un modelo de Markov se especifica identificando:

-   a\) los conjuntos de estados $S={1, ... , m}$,

-   b\) el conjunto de transiciones posibles, es decir, los pares $(i,j)$ oara los cuales $p_{ij}>0$,

-   c\) los valores numéricos de estos $p_{ij}$ son positivos

La cadena de Markov especificada por este modelo es una secuencia de variables aletorias $X_0, X_1, X_2,...,$ que toma valores en $S$, y que satisface

$$
\textbf{P}(X_{n+1} = j | X_n = i, X_{n-1}= i_{n-1}, ... ,X_0=i_0)=p_{ij},
$$ para todo $n$, todos los estados $i,j \in S$, y toda posible secuencia $i_0, ... , i_{n-1}$ de estados previos.

Todos los elementos de un modelo de cadena de Markov pueden codificarse en una **matrix de probabilidades de transición**, la cual es simplemente un arreglo bidimensional donde el elemento de la *i-jésima* fila y de la *j-ésima* columna es $p_{ij}$:

\begin{pmatrix}
p_{11} & p_{12} & p_{13} & \cdots & p_{1n} \\
p_{21} & p_{22} & p_{23} & \cdots & p_{2n} \\
p_{31} & p_{32} & p_{33} & \cdots & p_{3n} \\
\vdots & \vdots & \vdots & \ddots & \vdots \\
p_{n1} & p_{n2} & p_{n3} & \cdots & p_{nn}
\end{pmatrix}

donde $p_{ij}$ representa la probabilidad de transición del estado $i$ al estado $j$.

------------------------------------------------------------------------

### Ejemplo

Supongamos que existen dos regiones habitables: N y S. Además, existe movilidad de personas entre las dos regiones y un estudio realizado ha revelado que las siguientes proporciones de personas se quedan en su región o que migran a la otra región en un periodo dado:

\begin{pmatrix}
0.5 & 0.25 \\
0.5 & 0.75
\end{pmatrix}

### Definiciones

-   $N_t$ es la poblacion de la ciudad N en el momento t

-   $S_t$ es la poblacion de la ciudad S en el momento t

-   $X_t = N_t + S_t$

-   $\textbf{x}_t =$

    \begin{pmatrix} n_t \\ s_t \end{pmatrix}

-   $\textbf{I} =$

    \begin{pmatrix} 1 \\ 1 \end{pmatrix}

-   El vector fila con la misma información es $\textbf{I´}=\begin{pmatrix} 1&1 \end{pmatrix}$. De forma que:

$$
1=n_t +s_t= \begin{pmatrix} 1&1 \end{pmatrix} \begin{pmatrix} 1 \\ 1 \end{pmatrix} = \textbf{I}´\textbf{X}_t
$$

### Metodología

Representemos la información que tenemos como un sistema de ecuaciones lineales: $$
\begin{align}
n_t = 0.5 n_{t-1} + 0.25 s_{t-1} \\
s_t = 0.5 n_{t-1} + 0.75 s_{t-1}
\end{align}
$$
